- app/api/poll/route.ts
- app/form.tsx
- app/polls/[id]/page.tsx
- constants/index.ts
> refactor: naming

- app/form.tsx
- app/polls/[id]/page.tsx
- app/polls/page.tsx
> refactor: error msg

- middleware.ts
> feat: add cors headers

- src/app/api/frames/route.tsx
- src/helpers/createFrameErrorResponse.tsx
- src/helpers/withFrameRequestErrorHandler.ts
- src/locales/en/index.ts
- src/locales/zh/index.ts
> refactor: handle error

- src/app/api/frames/vote/route.tsx
- src/app/polls/[id]/page.tsx
- src/components/FrameTips.tsx
- src/helpers/parsePollWithZod.ts
https://mask.atlassian.net/browse/FW-1289
Closes #0000
> fix: data valid error

- src/app/api/frames/images/route.ts
- src/app/api/frames/route.tsx
- src/components/ErrorHandler.tsx
- src/components/PollCard.tsx
- src/constants/index.ts
- src/helpers/createFrameErrorResponse.tsx
- src/helpers/getButtonLabelFromErrorMessage.ts
- src/helpers/getLensFrameMessage.ts
- src/helpers/parsePollWithZod.ts
- src/helpers/withFrameRequestErrorHandler.ts
https://mask.atlassian.net/browse/FW-1298
Closes #0000
> fix: add zoom scale for image

- src/app/polls/[id]/page.tsx
- src/components/RedirectProfile.tsx
- src/constants/index.ts
https://mask.atlassian.net/browse/FW-1351
Closes #0000
> feat: redirect user when click frame link directly

- src/app/polls/[id]/page.tsx
> feat: add og image

- src/app/polls/[id]/page.tsx
> feat: support hey og

- src/components/PollCard.tsx
https://mask.atlassian.net/browse/FW-1389
Closes #0000
> fix: fix poll style error

- src/components/PollCard.tsx
- src/helpers/getPollTimeLeft.ts
- src/locales/en/index.ts
- src/locales/zh-Hans/index.ts
- src/locales/zh-Hant/index.ts
> fix: update poll duration text

- src/components/PollCard.tsx
- src/constants/zod.ts
- src/helpers/getPollFrameButtons.tsx
> feat: add ff profile link

- src/app/polls/[id]/page.tsx
- src/components/PollCard.tsx
- src/helpers/createFrameSuccessResponse.ts
> feat: try remove cache

- src/components/PollCard.tsx
> feat: hide time left when has no profile

- src/components/PollCard.tsx
> fix: poll status error

- src/locales/en/index.ts
- src/locales/zh-Hans/index.ts
- src/locales/zh-Hant/index.ts
> fix: translation words error

- src/components/PollCard.tsx
> fix: show vote counts when ended

- src/components/PollCard.tsx
- src/helpers/getPollFrameButtons.tsx
> feat: hidden poll when no profile applied

- src/helpers/getPollFrameButtons.tsx
- src/locales/en/index.ts
- src/locales/zh-Hans/index.ts
- src/locales/zh-Hant/index.ts
> fix: renaming text

- src/components/PollCard.tsx
- src/config/frames.ts
- src/helpers/createFrameSuccessResponse.ts
> fix: adjust optoin display length
